import Head from "next/head";
import Layout from "../components/Layout";
import Image from "next/image";
import profilePic from "./../img/dream_developer.png";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../components/Icons";
import { useRouter } from "next/router";
import HireMe from "../components/HireMe";

export default function Home() {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Alex Portfolio</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0">
                    <div className="flex items-center justify-between w-full">
                        <div className="w-1/2">
                            <Image
                                src={profilePic}
                                alt="Forerunner's generated profile pic"
                                className="w-auto h-auto m-auto rounded-full shadow-2xl"
                                priority
                                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"
                            />
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center">
                            <AnimatedText
                                text="Bonjour, je suis Alexandre Ribault"
                                className="!text-6xl !text-left"
                            />
                            <p className="my-4 text-base font-medium">
                                Je suis un développeur back-end mais un développeur curieux avant
                                tout. J'aime me diversifier, m'ouvrir à de nouvelles technologies.
                                N'hésitez pas à explorer mes différents projets et à me contacter si
                                vous avez des questions.
                            </p>
                            <div className="flex items-center self-start mt-2">
                                <Link
                                    href="/"
                                    // target="_blank"
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                                    // download={true}
                                >
                                    CV <LinkArrow className={"w-6 ml-1"} />
                                </Link>
                                <Link
                                    href="mailto:alex.ribault@gmail.com"
                                    className="relative group ml-4 text-lg font-medium capitalize text-dark dark:text-light"
                                >
                                    Contact
                                    <span
                                        className={`h-[2px] inline-block bg-dark dark:bg-light absolute left-0 -bottom-0.5 group-hover:w-full transition-[width] ease duration-300 ${
                                            router.asPath === "mailto:alex.ribault@gmail.com"
                                                ? "w-full"
                                                : "w-0"
                                        }`}
                                    ></span>
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <HireMe />
            </main>
        </>
    );
}
//beautifully drawn, developer working on his computer, digital art, profile picture, cosmic star background, watercolor, white background
